name: shop_deal
description: "Shop Deal is a full e-commerce cross platform application for mobile."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  cloud_firestore: ^4.14.0
  connectivity_plus: ^6.0.5
  dio: ^5.6.0
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.0.1
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  loading_animation_widget: ^1.2.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.1
  top_snackbar_flutter: ^3.1.0
  webview_flutter: ^4.8.0
  flutter_localizations:
        sdk: flutter
  intl: ^0.19.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.2
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/dark_mode_icons/
    - assets/images/app_icon/
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
          weight: 400
flutter_intl:
  enabled: true
